#define FPS 60.00
#define APS 120.00
#define SCREEN_W 800
#define SCREEN_H 600
#define IMAGE_SIZE_WIDTH 32
#define IMAGE_SIZE_HEIGHT 32
#define ACCELERATION 0.3
#define SPEED_LIMIT 5
#define SAMPLE_GAIN 1.0
#define SAMPLE_PAN 0
#define SAMPLE_SPEED 1.0
#define SAMPLE_PLAY_ONCE ALLEGRO_PLAYMODE_ONCE

enum MYKEYS {
	KEY_W, KEY_A, KEY_S, KEY_D, KEY_SPACE
};

enum GAME_STATUS {
	HOME, INSTRUCTIONS, LV1, LV2, LV3, NO_LIFE, WON
};
